"""Correction probatoire

Revision ID: 12cf8144e1d4
Revises: 9eb1f1112bed
Create Date: 2025-09-25 14:25:15.382009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12cf8144e1d4'
down_revision: Union[str, Sequence[str], None] = '9eb1f1112bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fnpc', sa.Column('probatoire', sa.Boolean(), nullable=True))
    op.add_column('fnpc', sa.Column('date_probatoire', sa.Date(), nullable=True))
    op.drop_index(op.f('ix_fnpc_date_propabatoire'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_propbatoire'), table_name='fnpc')
    op.create_index(op.f('ix_fnpc_date_probatoire'), 'fnpc', ['date_probatoire'], unique=False)
    op.create_index(op.f('ix_fnpc_probatoire'), 'fnpc', ['probatoire'], unique=False)
    op.drop_column('fnpc', 'date_propabatoire')
    op.drop_column('fnpc', 'propbatoire')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fnpc', sa.Column('propbatoire', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('fnpc', sa.Column('date_propabatoire', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_fnpc_probatoire'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_date_probatoire'), table_name='fnpc')
    op.create_index(op.f('ix_fnpc_propbatoire'), 'fnpc', ['propbatoire'], unique=False)
    op.create_index(op.f('ix_fnpc_date_propabatoire'), 'fnpc', ['date_propabatoire'], unique=False)
    op.drop_column('fnpc', 'date_probatoire')
    op.drop_column('fnpc', 'probatoire')
    # ### end Alembic commands ###
