"""Refonte Infractions

Revision ID: 1419345508da
Revises: 12cf8144e1d4
Create Date: 2025-09-25 17:43:35.942913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1419345508da'
down_revision: Union[str, Sequence[str], None] = '12cf8144e1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infractions_routieres', sa.Column('article', sa.String(), nullable=True))
    op.add_column('infractions_routieres', sa.Column('classe', sa.String(), nullable=True))
    op.add_column('infractions_routieres', sa.Column('nipol', sa.String(), nullable=True))
    op.add_column('infractions_routieres', sa.Column('date_infraction', sa.Date(), nullable=True))
    op.add_column('infractions_routieres', sa.Column('details', sa.String(), nullable=True))
    op.add_column('infractions_routieres', sa.Column('statut', sa.String(), nullable=True))
    op.drop_index(op.f('ix_infractions_routieres_code'), table_name='infractions_routieres')
    op.drop_index(op.f('ix_infractions_routieres_description'), table_name='infractions_routieres')
    op.create_index(op.f('ix_infractions_routieres_article'), 'infractions_routieres', ['article'], unique=False)
    op.create_index(op.f('ix_infractions_routieres_classe'), 'infractions_routieres', ['classe'], unique=False)
    op.create_index(op.f('ix_infractions_routieres_date_infraction'), 'infractions_routieres', ['date_infraction'], unique=False)
    op.create_index(op.f('ix_infractions_routieres_details'), 'infractions_routieres', ['details'], unique=False)
    op.create_index(op.f('ix_infractions_routieres_nipol'), 'infractions_routieres', ['nipol'], unique=False)
    op.create_index(op.f('ix_infractions_routieres_statut'), 'infractions_routieres', ['statut'], unique=False)
    op.drop_column('infractions_routieres', 'description')
    op.drop_column('infractions_routieres', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infractions_routieres', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infractions_routieres', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_infractions_routieres_statut'), table_name='infractions_routieres')
    op.drop_index(op.f('ix_infractions_routieres_nipol'), table_name='infractions_routieres')
    op.drop_index(op.f('ix_infractions_routieres_details'), table_name='infractions_routieres')
    op.drop_index(op.f('ix_infractions_routieres_date_infraction'), table_name='infractions_routieres')
    op.drop_index(op.f('ix_infractions_routieres_classe'), table_name='infractions_routieres')
    op.drop_index(op.f('ix_infractions_routieres_article'), table_name='infractions_routieres')
    op.create_index(op.f('ix_infractions_routieres_description'), 'infractions_routieres', ['description'], unique=False)
    op.create_index(op.f('ix_infractions_routieres_code'), 'infractions_routieres', ['code'], unique=False)
    op.drop_column('infractions_routieres', 'statut')
    op.drop_column('infractions_routieres', 'details')
    op.drop_column('infractions_routieres', 'date_infraction')
    op.drop_column('infractions_routieres', 'nipol')
    op.drop_column('infractions_routieres', 'classe')
    op.drop_column('infractions_routieres', 'article')
    # ### end Alembic commands ###
