"""Remove index on password

Revision ID: 166bf1e00fab
Revises: 2855b1aec972
Create Date: 2025-10-05 14:41:52.833879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166bf1e00fab'
down_revision: Union[str, Sequence[str], None] = '2855b1aec972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_password'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    # ### end Alembic commands ###
