"""inscription date et status

Revision ID: 18b338b2d4b1
Revises: b65935b90e7f
Create Date: 2025-09-06 14:20:32.067779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b338b2d4b1'
down_revision: Union[str, Sequence[str], None] = 'b65935b90e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('inscription_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('account_status', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_account_status'), 'users', ['account_status'], unique=False)
    op.create_index(op.f('ix_users_inscription_date'), 'users', ['inscription_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_inscription_date'), table_name='users')
    op.drop_index(op.f('ix_users_account_status'), table_name='users')
    op.drop_column('users', 'account_status')
    op.drop_column('users', 'inscription_date')
    # ### end Alembic commands ###
