"""Ajout CGU & RGPD

Revision ID: 1c0220c96c61
Revises: fc7a8364a764
Create Date: 2025-10-09 15:43:33.686434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0220c96c61'
down_revision: Union[str, Sequence[str], None] = 'fc7a8364a764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accepted_cgu', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('accepted_privacy', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accepted_privacy')
    op.drop_column('users', 'accepted_cgu')
    # ### end Alembic commands ###
