"""service

Revision ID: 268ed200fc41
Revises: 9871fcd3889f
Create Date: 2025-09-06 14:49:11.814802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '268ed200fc41'
down_revision: Union[str, Sequence[str], None] = '9871fcd3889f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rp_service', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_rp_service'), 'users', ['rp_service'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_rp_service'), table_name='users')
    op.drop_column('users', 'rp_service')
    # ### end Alembic commands ###
