"""Ajout SIV

Revision ID: 2855b1aec972
Revises: e66d889cd933
Create Date: 2025-10-01 15:08:55.997242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2855b1aec972'
down_revision: Union[str, Sequence[str], None] = 'e66d889cd933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prop_id', sa.Integer(), nullable=True),
    sa.Column('co_prop_id', sa.Integer(), nullable=True),
    sa.Column('ci_etat_administratif', sa.String(), nullable=True),
    sa.Column('ci_numero_immatriculation', sa.String(), nullable=True),
    sa.Column('ci_date_premiere_circulation', sa.Date(), nullable=True),
    sa.Column('ci_date_certificat', sa.Date(), nullable=True),
    sa.Column('vl_etat_administratif', sa.String(), nullable=True),
    sa.Column('vl_marque', sa.String(), nullable=True),
    sa.Column('vl_denomination_commerciale', sa.String(), nullable=True),
    sa.Column('vl_version', sa.String(), nullable=True),
    sa.Column('vl_couleur_dominante', sa.String(), nullable=True),
    sa.Column('tech_puissance_kw', sa.Integer(), nullable=True),
    sa.Column('tech_puissance_ch', sa.Integer(), nullable=True),
    sa.Column('tech_puissance_fiscale', sa.Integer(), nullable=True),
    sa.Column('tech_cylindree', sa.Integer(), nullable=True),
    sa.Column('tech_carburant', sa.String(), nullable=True),
    sa.Column('tech_emissions_co2', sa.Integer(), nullable=True),
    sa.Column('tech_poids_vide', sa.Integer(), nullable=True),
    sa.Column('tech_poids_ptac', sa.Integer(), nullable=True),
    sa.Column('tech_places_assises', sa.Integer(), nullable=True),
    sa.Column('tech_places_debout', sa.Integer(), nullable=True),
    sa.Column('ct_date_echeance', sa.Date(), nullable=True),
    sa.Column('as_assureur', sa.String(), nullable=True),
    sa.Column('as_date_contrat', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['co_prop_id'], ['proprietaires.id'], ),
    sa.ForeignKeyConstraint(['prop_id'], ['proprietaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_siv_as_assureur'), 'siv', ['as_assureur'], unique=False)
    op.create_index(op.f('ix_siv_as_date_contrat'), 'siv', ['as_date_contrat'], unique=False)
    op.create_index(op.f('ix_siv_ci_date_certificat'), 'siv', ['ci_date_certificat'], unique=False)
    op.create_index(op.f('ix_siv_ci_date_premiere_circulation'), 'siv', ['ci_date_premiere_circulation'], unique=False)
    op.create_index(op.f('ix_siv_ci_etat_administratif'), 'siv', ['ci_etat_administratif'], unique=False)
    op.create_index(op.f('ix_siv_ci_numero_immatriculation'), 'siv', ['ci_numero_immatriculation'], unique=False)
    op.create_index(op.f('ix_siv_ct_date_echeance'), 'siv', ['ct_date_echeance'], unique=False)
    op.create_index(op.f('ix_siv_id'), 'siv', ['id'], unique=False)
    op.create_index(op.f('ix_siv_tech_carburant'), 'siv', ['tech_carburant'], unique=False)
    op.create_index(op.f('ix_siv_tech_cylindree'), 'siv', ['tech_cylindree'], unique=False)
    op.create_index(op.f('ix_siv_tech_emissions_co2'), 'siv', ['tech_emissions_co2'], unique=False)
    op.create_index(op.f('ix_siv_tech_places_assises'), 'siv', ['tech_places_assises'], unique=False)
    op.create_index(op.f('ix_siv_tech_places_debout'), 'siv', ['tech_places_debout'], unique=False)
    op.create_index(op.f('ix_siv_tech_poids_ptac'), 'siv', ['tech_poids_ptac'], unique=False)
    op.create_index(op.f('ix_siv_tech_poids_vide'), 'siv', ['tech_poids_vide'], unique=False)
    op.create_index(op.f('ix_siv_tech_puissance_ch'), 'siv', ['tech_puissance_ch'], unique=False)
    op.create_index(op.f('ix_siv_tech_puissance_fiscale'), 'siv', ['tech_puissance_fiscale'], unique=False)
    op.create_index(op.f('ix_siv_tech_puissance_kw'), 'siv', ['tech_puissance_kw'], unique=False)
    op.create_index(op.f('ix_siv_vl_couleur_dominante'), 'siv', ['vl_couleur_dominante'], unique=False)
    op.create_index(op.f('ix_siv_vl_denomination_commerciale'), 'siv', ['vl_denomination_commerciale'], unique=False)
    op.create_index(op.f('ix_siv_vl_etat_administratif'), 'siv', ['vl_etat_administratif'], unique=False)
    op.create_index(op.f('ix_siv_vl_marque'), 'siv', ['vl_marque'], unique=False)
    op.create_index(op.f('ix_siv_vl_version'), 'siv', ['vl_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_siv_vl_version'), table_name='siv')
    op.drop_index(op.f('ix_siv_vl_marque'), table_name='siv')
    op.drop_index(op.f('ix_siv_vl_etat_administratif'), table_name='siv')
    op.drop_index(op.f('ix_siv_vl_denomination_commerciale'), table_name='siv')
    op.drop_index(op.f('ix_siv_vl_couleur_dominante'), table_name='siv')
    op.drop_index(op.f('ix_siv_tech_puissance_kw'), table_name='siv')
    op.drop_index(op.f('ix_siv_tech_puissance_fiscale'), table_name='siv')
    op.drop_index(op.f('ix_siv_tech_puissance_ch'), table_name='siv')
    op.drop_index(op.f('ix_siv_tech_poids_vide'), table_name='siv')
    op.drop_index(op.f('ix_siv_tech_poids_ptac'), table_name='siv')
    op.drop_index(op.f('ix_siv_tech_places_debout'), table_name='siv')
    op.drop_index(op.f('ix_siv_tech_places_assises'), table_name='siv')
    op.drop_index(op.f('ix_siv_tech_emissions_co2'), table_name='siv')
    op.drop_index(op.f('ix_siv_tech_cylindree'), table_name='siv')
    op.drop_index(op.f('ix_siv_tech_carburant'), table_name='siv')
    op.drop_index(op.f('ix_siv_id'), table_name='siv')
    op.drop_index(op.f('ix_siv_ct_date_echeance'), table_name='siv')
    op.drop_index(op.f('ix_siv_ci_numero_immatriculation'), table_name='siv')
    op.drop_index(op.f('ix_siv_ci_etat_administratif'), table_name='siv')
    op.drop_index(op.f('ix_siv_ci_date_premiere_circulation'), table_name='siv')
    op.drop_index(op.f('ix_siv_ci_date_certificat'), table_name='siv')
    op.drop_index(op.f('ix_siv_as_date_contrat'), table_name='siv')
    op.drop_index(op.f('ix_siv_as_assureur'), table_name='siv')
    op.drop_table('siv')
    # ### end Alembic commands ###
