"""Unificate rp_nipol

Revision ID: 3bf2a241c150
Revises: 92862af002e0
Create Date: 2025-09-13 23:54:15.389452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf2a241c150'
down_revision: Union[str, Sequence[str], None] = '92862af002e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'rp_nipol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_rp_nipol'), table_name='users')
    op.create_index(op.f('ix_users_rp_nipol'), 'users', ['rp_nipol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_rp_nipol'), table_name='users')
    op.create_index(op.f('ix_users_rp_nipol'), 'users', ['rp_nipol'], unique=False)
    op.alter_column('users', 'rp_nipol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
