"""Ajout Natinf

Revision ID: 66432557ff96
Revises: 1419345508da
Create Date: 2025-09-25 21:21:59.202114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66432557ff96'
down_revision: Union[str, Sequence[str], None] = '1419345508da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infractions_routieres', sa.Column('natinf', sa.String(), nullable=True))
    op.create_index(op.f('ix_infractions_routieres_natinf'), 'infractions_routieres', ['natinf'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_infractions_routieres_natinf'), table_name='infractions_routieres')
    op.drop_column('infractions_routieres', 'natinf')
    # ### end Alembic commands ###
