"""Suppresion isAdmin et ajout Gender

Revision ID: 8213a0efa4bd
Revises: 268ed200fc41
Create Date: 2025-09-10 21:44:34.929527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8213a0efa4bd'
down_revision: Union[str, Sequence[str], None] = '268ed200fc41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rp_gender', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_rp_gender'), 'users', ['rp_gender'], unique=False)
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_rp_gender'), table_name='users')
    op.drop_column('users', 'rp_gender')
    # ### end Alembic commands ###
