"""Vérification Temp Password

Revision ID: 92862af002e0
Revises: b2e533c856a9
Create Date: 2025-09-13 22:49:01.586876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92862af002e0'
down_revision: Union[str, Sequence[str], None] = 'b2e533c856a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('temp_password', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'temp_password')
    # ### end Alembic commands ###
