"""inscription status modif

Revision ID: 9871fcd3889f
Revises: 18b338b2d4b1
Create Date: 2025-09-06 14:32:58.308239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9871fcd3889f'
down_revision: Union[str, Sequence[str], None] = '18b338b2d4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('inscription_status', sa.String(), nullable=True))
    op.drop_index(op.f('ix_users_account_status'), table_name='users')
    op.create_index(op.f('ix_users_inscription_status'), 'users', ['inscription_status'], unique=False)
    op.drop_column('users', 'account_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_inscription_status'), table_name='users')
    op.create_index(op.f('ix_users_account_status'), 'users', ['account_status'], unique=False)
    op.drop_column('users', 'inscription_status')
    # ### end Alembic commands ###
