"""ajout Prefecture Delivrance

Revision ID: 9eb1f1112bed
Revises: c01fa60fea22
Create Date: 2025-09-22 17:55:51.057134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb1f1112bed'
down_revision: Union[str, Sequence[str], None] = 'c01fa60fea22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fnpc', sa.Column('prefecture_delivrance', sa.String(), nullable=True))
    op.create_index(op.f('ix_fnpc_prefecture_delivrance'), 'fnpc', ['prefecture_delivrance'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fnpc_prefecture_delivrance'), table_name='fnpc')
    op.drop_column('fnpc', 'prefecture_delivrance')
    # ### end Alembic commands ###
