"""add_token_version

Revision ID: b2e533c856a9
Revises: 8213a0efa4bd
Create Date: 2025-09-11 17:07:28.909826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e533c856a9'
down_revision: Union[str, Sequence[str], None] = '8213a0efa4bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
