"""Discord ID

Revision ID: b65935b90e7f
Revises: f28db8ef1425
Create Date: 2025-09-05 23:57:21.744326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b65935b90e7f'
down_revision: Union[str, Sequence[str], None] = 'f28db8ef1425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('discord_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.drop_column('users', 'discord_id')
    # ### end Alembic commands ###
