"""ajout FNPC et Infractions

Revision ID: c01fa60fea22
Revises: e52e2d0428d7
Create Date: 2025-09-22 17:50:39.751594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01fa60fea22'
down_revision: Union[str, Sequence[str], None] = 'e52e2d0428d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fnpc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neph', sa.Integer(), nullable=True),
    sa.Column('numero_titre', sa.Integer(), nullable=True),
    sa.Column('date_delivrance', sa.Date(), nullable=True),
    sa.Column('date_expiration', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('validite', sa.String(), nullable=True),
    sa.Column('cat_am', sa.Boolean(), nullable=True),
    sa.Column('cat_am_delivrance', sa.Date(), nullable=True),
    sa.Column('cat_a1', sa.Boolean(), nullable=True),
    sa.Column('cat_a1_delivrance', sa.Date(), nullable=True),
    sa.Column('cat_a2', sa.Boolean(), nullable=True),
    sa.Column('cat_a2_delivrance', sa.Date(), nullable=True),
    sa.Column('cat_a', sa.Boolean(), nullable=True),
    sa.Column('cat_a_delivrance', sa.Date(), nullable=True),
    sa.Column('cat_b1', sa.Boolean(), nullable=True),
    sa.Column('cat_b1_delivrance', sa.Date(), nullable=True),
    sa.Column('cat_b', sa.Boolean(), nullable=True),
    sa.Column('cat_b_delivrance', sa.Date(), nullable=True),
    sa.Column('cat_c1', sa.Boolean(), nullable=True),
    sa.Column('cat_c1_delivrance', sa.Date(), nullable=True),
    sa.Column('cat_c', sa.Boolean(), nullable=True),
    sa.Column('cat_c_delivrance', sa.Date(), nullable=True),
    sa.Column('cat_d1', sa.Boolean(), nullable=True),
    sa.Column('cat_d1_delivrance', sa.Date(), nullable=True),
    sa.Column('cat_d', sa.Boolean(), nullable=True),
    sa.Column('cat_d_delivrance', sa.Date(), nullable=True),
    sa.Column('cat_be', sa.Boolean(), nullable=True),
    sa.Column('cat_be_delivrance', sa.Date(), nullable=True),
    sa.Column('cat_c1e', sa.Boolean(), nullable=True),
    sa.Column('cat_c1e_delivrance', sa.Date(), nullable=True),
    sa.Column('cat_ce', sa.Boolean(), nullable=True),
    sa.Column('cat_ce_delivrance', sa.Date(), nullable=True),
    sa.Column('cat_d1e', sa.Boolean(), nullable=True),
    sa.Column('cat_d1e_delivrance', sa.Date(), nullable=True),
    sa.Column('cat_de', sa.Boolean(), nullable=True),
    sa.Column('cat_de_delivrance', sa.Date(), nullable=True),
    sa.Column('code_restriction', sa.String(), nullable=True),
    sa.Column('propbatoire', sa.Boolean(), nullable=True),
    sa.Column('date_propabatoire', sa.Date(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('prop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prop_id'], ['proprietaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fnpc_cat_a'), 'fnpc', ['cat_a'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_a1'), 'fnpc', ['cat_a1'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_a1_delivrance'), 'fnpc', ['cat_a1_delivrance'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_a2'), 'fnpc', ['cat_a2'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_a2_delivrance'), 'fnpc', ['cat_a2_delivrance'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_a_delivrance'), 'fnpc', ['cat_a_delivrance'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_am'), 'fnpc', ['cat_am'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_am_delivrance'), 'fnpc', ['cat_am_delivrance'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_b'), 'fnpc', ['cat_b'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_b1'), 'fnpc', ['cat_b1'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_b1_delivrance'), 'fnpc', ['cat_b1_delivrance'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_b_delivrance'), 'fnpc', ['cat_b_delivrance'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_be'), 'fnpc', ['cat_be'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_be_delivrance'), 'fnpc', ['cat_be_delivrance'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_c'), 'fnpc', ['cat_c'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_c1'), 'fnpc', ['cat_c1'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_c1_delivrance'), 'fnpc', ['cat_c1_delivrance'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_c1e'), 'fnpc', ['cat_c1e'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_c1e_delivrance'), 'fnpc', ['cat_c1e_delivrance'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_c_delivrance'), 'fnpc', ['cat_c_delivrance'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_ce'), 'fnpc', ['cat_ce'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_ce_delivrance'), 'fnpc', ['cat_ce_delivrance'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_d'), 'fnpc', ['cat_d'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_d1'), 'fnpc', ['cat_d1'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_d1_delivrance'), 'fnpc', ['cat_d1_delivrance'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_d1e'), 'fnpc', ['cat_d1e'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_d1e_delivrance'), 'fnpc', ['cat_d1e_delivrance'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_d_delivrance'), 'fnpc', ['cat_d_delivrance'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_de'), 'fnpc', ['cat_de'], unique=False)
    op.create_index(op.f('ix_fnpc_cat_de_delivrance'), 'fnpc', ['cat_de_delivrance'], unique=False)
    op.create_index(op.f('ix_fnpc_code_restriction'), 'fnpc', ['code_restriction'], unique=False)
    op.create_index(op.f('ix_fnpc_date_delivrance'), 'fnpc', ['date_delivrance'], unique=False)
    op.create_index(op.f('ix_fnpc_date_expiration'), 'fnpc', ['date_expiration'], unique=False)
    op.create_index(op.f('ix_fnpc_date_propabatoire'), 'fnpc', ['date_propabatoire'], unique=False)
    op.create_index(op.f('ix_fnpc_id'), 'fnpc', ['id'], unique=False)
    op.create_index(op.f('ix_fnpc_neph'), 'fnpc', ['neph'], unique=True)
    op.create_index(op.f('ix_fnpc_numero_titre'), 'fnpc', ['numero_titre'], unique=False)
    op.create_index(op.f('ix_fnpc_points'), 'fnpc', ['points'], unique=False)
    op.create_index(op.f('ix_fnpc_propbatoire'), 'fnpc', ['propbatoire'], unique=False)
    op.create_index(op.f('ix_fnpc_statut'), 'fnpc', ['statut'], unique=False)
    op.create_index(op.f('ix_fnpc_validite'), 'fnpc', ['validite'], unique=False)
    op.create_table('infractions_routieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('neph', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['neph'], ['fnpc.neph'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infractions_routieres_code'), 'infractions_routieres', ['code'], unique=False)
    op.create_index(op.f('ix_infractions_routieres_description'), 'infractions_routieres', ['description'], unique=False)
    op.create_index(op.f('ix_infractions_routieres_id'), 'infractions_routieres', ['id'], unique=False)
    op.create_index(op.f('ix_infractions_routieres_points'), 'infractions_routieres', ['points'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_infractions_routieres_points'), table_name='infractions_routieres')
    op.drop_index(op.f('ix_infractions_routieres_id'), table_name='infractions_routieres')
    op.drop_index(op.f('ix_infractions_routieres_description'), table_name='infractions_routieres')
    op.drop_index(op.f('ix_infractions_routieres_code'), table_name='infractions_routieres')
    op.drop_table('infractions_routieres')
    op.drop_index(op.f('ix_fnpc_validite'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_statut'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_propbatoire'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_points'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_numero_titre'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_neph'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_id'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_date_propabatoire'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_date_expiration'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_date_delivrance'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_code_restriction'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_de_delivrance'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_de'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_d_delivrance'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_d1e_delivrance'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_d1e'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_d1_delivrance'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_d1'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_d'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_ce_delivrance'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_ce'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_c_delivrance'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_c1e_delivrance'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_c1e'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_c1_delivrance'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_c1'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_c'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_be_delivrance'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_be'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_b_delivrance'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_b1_delivrance'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_b1'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_b'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_am_delivrance'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_am'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_a_delivrance'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_a2_delivrance'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_a2'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_a1_delivrance'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_a1'), table_name='fnpc')
    op.drop_index(op.f('ix_fnpc_cat_a'), table_name='fnpc')
    op.drop_table('fnpc')
    # ### end Alembic commands ###
