"""Ajout FPR

Revision ID: d0b50020ca4d
Revises: a628b9efc5db
Create Date: 2025-09-27 11:38:15.253327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b50020ca4d'
down_revision: Union[str, Sequence[str], None] = 'a628b9efc5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fpr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exactitude', sa.String(), nullable=True),
    sa.Column('date_enregistrement', sa.Date(), nullable=True),
    sa.Column('motif_enregistrement', sa.String(), nullable=True),
    sa.Column('autorite_enregistrement', sa.String(), nullable=True),
    sa.Column('lieu_faits', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('dangerosite', sa.String(), nullable=True),
    sa.Column('signes_distinctifs', sa.String(), nullable=True),
    sa.Column('conduite', sa.String(), nullable=True),
    sa.Column('id_prop', sa.Integer(), nullable=True),
    sa.Column('neph', sa.BigInteger(), nullable=True),
    sa.Column('num_fijait', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_prop'], ['proprietaires.id'], ),
    sa.ForeignKeyConstraint(['neph'], ['fnpc.neph'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fpr_autorite_enregistrement'), 'fpr', ['autorite_enregistrement'], unique=False)
    op.create_index(op.f('ix_fpr_conduite'), 'fpr', ['conduite'], unique=False)
    op.create_index(op.f('ix_fpr_dangerosite'), 'fpr', ['dangerosite'], unique=False)
    op.create_index(op.f('ix_fpr_date_enregistrement'), 'fpr', ['date_enregistrement'], unique=False)
    op.create_index(op.f('ix_fpr_details'), 'fpr', ['details'], unique=False)
    op.create_index(op.f('ix_fpr_exactitude'), 'fpr', ['exactitude'], unique=False)
    op.create_index(op.f('ix_fpr_id'), 'fpr', ['id'], unique=False)
    op.create_index(op.f('ix_fpr_lieu_faits'), 'fpr', ['lieu_faits'], unique=False)
    op.create_index(op.f('ix_fpr_motif_enregistrement'), 'fpr', ['motif_enregistrement'], unique=False)
    op.create_index(op.f('ix_fpr_signes_distinctifs'), 'fpr', ['signes_distinctifs'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fpr_signes_distinctifs'), table_name='fpr')
    op.drop_index(op.f('ix_fpr_motif_enregistrement'), table_name='fpr')
    op.drop_index(op.f('ix_fpr_lieu_faits'), table_name='fpr')
    op.drop_index(op.f('ix_fpr_id'), table_name='fpr')
    op.drop_index(op.f('ix_fpr_exactitude'), table_name='fpr')
    op.drop_index(op.f('ix_fpr_details'), table_name='fpr')
    op.drop_index(op.f('ix_fpr_date_enregistrement'), table_name='fpr')
    op.drop_index(op.f('ix_fpr_dangerosite'), table_name='fpr')
    op.drop_index(op.f('ix_fpr_conduite'), table_name='fpr')
    op.drop_index(op.f('ix_fpr_autorite_enregistrement'), table_name='fpr')
    op.drop_table('fpr')
    # ### end Alembic commands ###
