"""Create proprietaires

Revision ID: e52e2d0428d7
Revises: 86039abc2b93
Create Date: 2025-09-14 00:49:44.354845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52e2d0428d7'
down_revision: Union[str, Sequence[str], None] = '86039abc2b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proprietaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_famille', sa.String(), nullable=True),
    sa.Column('nom_usage', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('second_prenom', sa.String(), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('sexe', sa.String(), nullable=True),
    sa.Column('lieu_naissance', sa.String(), nullable=True),
    sa.Column('departement_naissance_numero', sa.Integer(), nullable=True),
    sa.Column('adresse_numero', sa.Integer(), nullable=True),
    sa.Column('adresse_type_voie', sa.String(), nullable=True),
    sa.Column('adresse_nom_voie', sa.String(), nullable=True),
    sa.Column('adresse_code_postal', sa.String(), nullable=True),
    sa.Column('adresse_commune', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proprietaires_adresse_code_postal'), 'proprietaires', ['adresse_code_postal'], unique=False)
    op.create_index(op.f('ix_proprietaires_adresse_commune'), 'proprietaires', ['adresse_commune'], unique=False)
    op.create_index(op.f('ix_proprietaires_adresse_nom_voie'), 'proprietaires', ['adresse_nom_voie'], unique=False)
    op.create_index(op.f('ix_proprietaires_adresse_numero'), 'proprietaires', ['adresse_numero'], unique=False)
    op.create_index(op.f('ix_proprietaires_adresse_type_voie'), 'proprietaires', ['adresse_type_voie'], unique=False)
    op.create_index(op.f('ix_proprietaires_date_naissance'), 'proprietaires', ['date_naissance'], unique=False)
    op.create_index(op.f('ix_proprietaires_departement_naissance_numero'), 'proprietaires', ['departement_naissance_numero'], unique=False)
    op.create_index(op.f('ix_proprietaires_id'), 'proprietaires', ['id'], unique=False)
    op.create_index(op.f('ix_proprietaires_lieu_naissance'), 'proprietaires', ['lieu_naissance'], unique=False)
    op.create_index(op.f('ix_proprietaires_nom_famille'), 'proprietaires', ['nom_famille'], unique=False)
    op.create_index(op.f('ix_proprietaires_nom_usage'), 'proprietaires', ['nom_usage'], unique=False)
    op.create_index(op.f('ix_proprietaires_prenom'), 'proprietaires', ['prenom'], unique=False)
    op.create_index(op.f('ix_proprietaires_second_prenom'), 'proprietaires', ['second_prenom'], unique=False)
    op.create_index(op.f('ix_proprietaires_sexe'), 'proprietaires', ['sexe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proprietaires_sexe'), table_name='proprietaires')
    op.drop_index(op.f('ix_proprietaires_second_prenom'), table_name='proprietaires')
    op.drop_index(op.f('ix_proprietaires_prenom'), table_name='proprietaires')
    op.drop_index(op.f('ix_proprietaires_nom_usage'), table_name='proprietaires')
    op.drop_index(op.f('ix_proprietaires_nom_famille'), table_name='proprietaires')
    op.drop_index(op.f('ix_proprietaires_lieu_naissance'), table_name='proprietaires')
    op.drop_index(op.f('ix_proprietaires_id'), table_name='proprietaires')
    op.drop_index(op.f('ix_proprietaires_departement_naissance_numero'), table_name='proprietaires')
    op.drop_index(op.f('ix_proprietaires_date_naissance'), table_name='proprietaires')
    op.drop_index(op.f('ix_proprietaires_adresse_type_voie'), table_name='proprietaires')
    op.drop_index(op.f('ix_proprietaires_adresse_numero'), table_name='proprietaires')
    op.drop_index(op.f('ix_proprietaires_adresse_nom_voie'), table_name='proprietaires')
    op.drop_index(op.f('ix_proprietaires_adresse_commune'), table_name='proprietaires')
    op.drop_index(op.f('ix_proprietaires_adresse_code_postal'), table_name='proprietaires')
    op.drop_table('proprietaires')
    # ### end Alembic commands ###
