"""Correction Prop Id

Revision ID: e66d889cd933
Revises: d0b50020ca4d
Create Date: 2025-09-27 14:27:44.850981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66d889cd933'
down_revision: Union[str, Sequence[str], None] = 'd0b50020ca4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fpr', sa.Column('prop_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('fpr_id_prop_fkey'), 'fpr', type_='foreignkey')
    op.create_foreign_key(None, 'fpr', 'proprietaires', ['prop_id'], ['id'])
    op.drop_column('fpr', 'id_prop')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fpr', sa.Column('id_prop', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fpr', type_='foreignkey')
    op.create_foreign_key(op.f('fpr_id_prop_fkey'), 'fpr', 'proprietaires', ['id_prop'], ['id'])
    op.drop_column('fpr', 'prop_id')
    # ### end Alembic commands ###
