"""Complete Users Model

Revision ID: f28db8ef1425
Revises: 3c44601c199f
Create Date: 2025-09-05 14:58:43.205326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28db8ef1425'
down_revision: Union[str, Sequence[str], None] = '3c44601c199f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rp_first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('rp_last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('rp_birthdate', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('rp_grade', sa.String(), nullable=True))
    op.add_column('users', sa.Column('rp_affectation', sa.String(), nullable=True))
    op.add_column('users', sa.Column('rp_qualif', sa.String(), nullable=True))
    op.add_column('users', sa.Column('rp_nipol', sa.String(), nullable=True))
    op.add_column('users', sa.Column('rp_server', sa.String(), nullable=True))
    op.add_column('users', sa.Column('privileges', sa.String(), nullable=True))
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_privileges'), 'users', ['privileges'], unique=False)
    op.create_index(op.f('ix_users_rp_affectation'), 'users', ['rp_affectation'], unique=False)
    op.create_index(op.f('ix_users_rp_birthdate'), 'users', ['rp_birthdate'], unique=False)
    op.create_index(op.f('ix_users_rp_first_name'), 'users', ['rp_first_name'], unique=False)
    op.create_index(op.f('ix_users_rp_grade'), 'users', ['rp_grade'], unique=False)
    op.create_index(op.f('ix_users_rp_last_name'), 'users', ['rp_last_name'], unique=False)
    op.create_index(op.f('ix_users_rp_nipol'), 'users', ['rp_nipol'], unique=False)
    op.create_index(op.f('ix_users_rp_qualif'), 'users', ['rp_qualif'], unique=False)
    op.create_index(op.f('ix_users_rp_server'), 'users', ['rp_server'], unique=False)
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_rp_server'), table_name='users')
    op.drop_index(op.f('ix_users_rp_qualif'), table_name='users')
    op.drop_index(op.f('ix_users_rp_nipol'), table_name='users')
    op.drop_index(op.f('ix_users_rp_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_rp_grade'), table_name='users')
    op.drop_index(op.f('ix_users_rp_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_rp_birthdate'), table_name='users')
    op.drop_index(op.f('ix_users_rp_affectation'), table_name='users')
    op.drop_index(op.f('ix_users_privileges'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.drop_column('users', 'privileges')
    op.drop_column('users', 'rp_server')
    op.drop_column('users', 'rp_nipol')
    op.drop_column('users', 'rp_qualif')
    op.drop_column('users', 'rp_affectation')
    op.drop_column('users', 'rp_grade')
    op.drop_column('users', 'rp_birthdate')
    op.drop_column('users', 'rp_last_name')
    op.drop_column('users', 'rp_first_name')
    # ### end Alembic commands ###
